export let results = [
  {
    KRA: "Delivery",
    KPI: "Actual vs Estimated delivery time (Task wise)",
    "Remarks_/_Scoring_Logic": "",
    Unit: "%",
    Type_of_KPI: "Negative",
    Weightage: "20",
    Target: "22",
    Appraisee_Self_Rating: "8",
    Appraisee_Marks: "90",
    Appraiser_Rating: "08",
    Appraiser_Marks: "20",
    Reviewer_Marks: "08",
  },
  {
    KRA: "",
    KPI: "On time successful delivery vs Total deliveries (Sprint wise)",
    "Remarks_/_Scoring_Logic": "Sticking to deadlines. Delivering ontime",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "15",
    Target: "20",
    Appraisee_Self_Rating: "08",
    Appraisee_Marks: "9",
    Appraiser_Rating: "08",
    Appraiser_Marks: "11.25",
    Reviewer_Marks: "08",
  },
  {
    KRA: "Quality",
    KPI: "Standards Compliance 100%",
    "Remarks_/_Scoring_Logic":
      "Adherence to the shedule of master list of drawings, Using file names in a specific format, Delivering results in a certain resolution, Delivering and achieving source files, Using brand colors, fonts, styles",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "5",
    Target: "20",
    Appraisee_Self_Rating: "100",
    Appraisee_Marks: "5",
    Appraiser_Rating: "08",
    Appraiser_Marks: "4.5",
    Reviewer_Marks: "08",
  },
  {
    KRA: "",
    KPI: "System usuability score should be >4",
    "Remarks_/_Scoring_Logic": "",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "10",
    Target: "20",
    Appraisee_Self_Rating: "4",
    Appraisee_Marks: "9",
    Appraiser_Rating: "08",
    Appraiser_Marks: "5",
    Reviewer_Marks: "08",
  },
  {
    KRA: "Productivity",
    KPI: "Revision/Re-do work time or hours <=2 hours (Per Project)",
    "Remarks_/_Scoring_Logic":
      "Number of revisions on the drawing submitted to the Estimation Dept and Site Execution Team. Can't do/have silly/basic/crtical mistakes",
    Unit: "%",
    Type_of_KPI: "Negative",
    Weightage: "20",
    Target: "100",
    Appraisee_Self_Rating: "2",
    Appraisee_Marks: "9",
    Appraiser_Rating: "08",
    Appraiser_Marks: "20",
    Reviewer_Marks: "08",
  },
  {
    KRA: "",
    KPI: "Train atleast 1 intern per quarter",
    "Remarks_/_Scoring_Logic": "",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "10",
    Target: "20",
    Appraisee_Self_Rating: "08",
    Appraisee_Marks: "9",
    Appraiser_Rating: "08",
    Appraiser_Marks: "20",
    Reviewer_Marks: "08",
  },
  {
    KRA: "",
    KPI: "Customer satisfaction: Rating >  4.5",
    "Remarks_/_Scoring_Logic": "",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "10",
    Target: "20",
    Appraisee_Self_Rating: "5",
    Appraisee_Marks: "11.11111111111111",
    Appraiser_Rating: "",
    Appraiser_Marks: "2.2222222222222214",
    Reviewer_Marks: "08",
  },
  {
    KRA: "Mandatory Clause",
    KPI: "Upskilling of Individual Learnings (Wtg-5)and of subordinates (Wtg-5). Benchmark 1 number in a year",
    "Remarks_/_Scoring_Logic":
      "Learn one new thing/new technology every 6months",
    Unit: "%",
    Type_of_KPI: "Positive",
    Weightage: "10",
    Target: "20",
    Appraisee_Self_Rating: "8",
    Appraisee_Marks: "10",
    Appraiser_Rating: "08",
    Appraiser_Marks: "10",
    Reviewer_Marks: "08",
  },
];
