let data = [
    {
       "Id": 9,
       "KRA": "Delivery",
       "KPI": "Actual vs Estimated delivery time (Task wise)",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "100",
       "Appraisee_Self_Rating": "1800",
       "Appraisee_Marks": "102.5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 10,
       "KRA": "",
       "KPI": "On time successful delivery vs Total deliveries (Sprint wise)",
       "Remarks_/_Scoring_Logic": "Sticking to deadlines. Delivering ontime",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "15",
       "Target": "20",
       "Appraisee_Self_Rating": "260",
       "Appraisee_Marks": "24.799999999999997",
       "Appraiser_Rating": "23.85",
       "Appraiser_Marks": "11.25",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 11,
       "KRA": "Quality",
       "KPI": "Standards Compliance 100%",
       "Remarks_/_Scoring_Logic": "Adherence to the shedule of master list of drawings, Using file names in a specific format, Delivering results in a certain resolution, Delivering and achieving source files, Using brand colors, fonts, styles",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "5",
       "Target": "100",
       "Appraisee_Self_Rating": "1000",
       "Appraisee_Marks": "5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "4.5",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 12,
       "KRA": "",
       "KPI": "System usuability score should be >4",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4",
       "Appraisee_Self_Rating": "40",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "5",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 13,
       "KRA": "Productivity",
       "KPI": "Revision/Re-do work time or hours <=2 hours (Per Project)",
       "Remarks_/_Scoring_Logic": "Number of revisions on the drawing submitted to the Estimation Dept and Site Execution Team. Can't do/have silly/basic/crtical mistakes",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "2",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 14,
       "KRA": "",
       "KPI": "Train atleast 1 intern per quarter",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 15,
       "KRA": "",
       "KPI": "Customer satisfaction: Rating >  4.5",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4.5",
       "Appraisee_Self_Rating": "52",
       "Appraisee_Marks": "11.11111111111111",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "2.2222222222222214",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 16,
       "KRA": "Mandatory Clause",
       "KPI": "Upskilling of Individual Learnings (Wtg-5)and of subordinates (Wtg-5). Benchmark 1 number in a year",
       "Remarks_/_Scoring_Logic": "Learn one new thing/new technology every 6months",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "220",
       "Appraisee_Marks": "10",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "10",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-07-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 9,
       "KRA": "Delivery",
       "KPI": "Actual vs Estimated delivery time (Task wise)",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "100",
       "Appraisee_Self_Rating": "1800",
       "Appraisee_Marks": "102.5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 10,
       "KRA": "",
       "KPI": "On time successful delivery vs Total deliveries (Sprint wise)",
       "Remarks_/_Scoring_Logic": "Sticking to deadlines. Delivering ontime",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "15",
       "Target": "20",
       "Appraisee_Self_Rating": "260",
       "Appraisee_Marks": "24.799999999999997",
       "Appraiser_Rating": "23.85",
       "Appraiser_Marks": "11.25",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
      "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 11,
       "KRA": "Quality",
       "KPI": "Standards Compliance 100%",
       "Remarks_/_Scoring_Logic": "Adherence to the shedule of master list of drawings, Using file names in a specific format, Delivering results in a certain resolution, Delivering and achieving source files, Using brand colors, fonts, styles",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "5",
       "Target": "100",
       "Appraisee_Self_Rating": "1000",
       "Appraisee_Marks": "5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "4.5",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
     "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 12,
       "KRA": "",
       "KPI": "System usuability score should be >4",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4",
       "Appraisee_Self_Rating": "40",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "5",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
       "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 13,
       "KRA": "Productivity",
       "KPI": "Revision/Re-do work time or hours <=2 hours (Per Project)",
       "Remarks_/_Scoring_Logic": "Number of revisions on the drawing submitted to the Estimation Dept and Site Execution Team. Can't do/have silly/basic/crtical mistakes",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "2",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
      "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 14,
       "KRA": "",
       "KPI": "Train atleast 1 intern per quarter",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
      "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 15,
       "KRA": "",
       "KPI": "Customer satisfaction: Rating >  4.5",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4.5",
       "Appraisee_Self_Rating": "52",
       "Appraisee_Marks": "11.11111111111111",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "2.2222222222222214",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
      "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   },
   {
       "Id": 16,
       "KRA": "Mandatory Clause",
       "KPI": "Upskilling of Individual Learnings (Wtg-5)and of subordinates (Wtg-5). Benchmark 1 number in a year",
       "Remarks_/_Scoring_Logic": "Learn one new thing/new technology every 6months",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "220",
       "Appraisee_Marks": "10",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "10",
       "Reviewer_Marks": "10",
       "ToUserId": "kumari.nikita@qservicesit.com",
       "FromUserId": "deepin.garg@qservicesit.com",
      "ToDate": "2022-08-31",
       "FromDate": "2022-07-01",
       "UpdatedDate": "2023-10-03 19:08:12",
       "CreatedDate": "2023-10-03 19:08:12",
       "ShowDevOpsData": "0",
       "IsEditable": "0",
       "IsReviewKey": "1",
       "isExactData": "0"
   }
]


  let sum = {
       Appraisee_Self_Rating: [],
       Appraiser_Rating: [],
       Target: [],
       Reviewer_Marks: [],
     };

     const groupedData = data.reduce((result, item) => {
       const toDate = item?.ToDate;
       if (!result[toDate]) {
         result[toDate] = [];
       }
       result[toDate].push(item);
       return result;
     }, {});


     Object.values(groupedData).forEach((data, index) => {
       data.forEach((allData, allindex) => {
         sum.Appraisee_Self_Rating[allindex] =
           (sum.Appraisee_Self_Rating[allindex] || 0) +
           parseFloat(allData?.Appraisee_Self_Rating);
         sum.Appraiser_Rating[allindex] =
           (sum.Appraiser_Rating[allindex] || 0) +
           parseFloat(allData?.Appraiser_Rating);
         sum.Target[allindex] =
           (sum.Target[allindex] || 0) + parseFloat(allData?.Target);
         sum.Reviewer_Marks[allindex] =
           (sum.Reviewer_Marks[allindex] || 0) +
           parseFloat(allData?.Reviewer_Marks);
       });
     });
     
   let newData = [
   {
       "KRA": "Delivery",
       "KPI": "Actual vs Estimated delivery time (Task wise)",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "100",
       "Appraisee_Self_Rating": "1800",
       "Appraisee_Marks": "102.5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "",
       "KPI": "On time successful delivery vs Total deliveries (Sprint wise)",
       "Remarks_/_Scoring_Logic": "Sticking to deadlines. Delivering ontime",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "15",
       "Target": "20",
       "Appraisee_Self_Rating": "260",
       "Appraisee_Marks": "24.799999999999997",
       "Appraiser_Rating": "23.85",
       "Appraiser_Marks": "11.25",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "Quality",
       "KPI": "Standards Compliance 100%",
       "Remarks_/_Scoring_Logic": "Adherence to the shedule of master list of drawings, Using file names in a specific format, Delivering results in a certain resolution, Delivering and achieving source files, Using brand colors, fonts, styles",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "5",
       "Target": "100",
       "Appraisee_Self_Rating": "1000",
       "Appraisee_Marks": "5",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "4.5",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "",
       "KPI": "System usuability score should be >4",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4",
       "Appraisee_Self_Rating": "40",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "5",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "Productivity",
       "KPI": "Revision/Re-do work time or hours <=2 hours (Per Project)",
       "Remarks_/_Scoring_Logic": "Number of revisions on the drawing submitted to the Estimation Dept and Site Execution Team. Can't do/have silly/basic/crtical mistakes",
       "Unit": "%",
       "Type_of_KPI": "Negative",
       "Weightage": "20",
       "Target": "2",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "",
       "KPI": "Train atleast 1 intern per quarter",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "20",
       "Appraisee_Marks": "",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "20",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "",
       "KPI": "Customer satisfaction: Rating >  4.5",
       "Remarks_/_Scoring_Logic": "",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "4.5",
       "Appraisee_Self_Rating": "52",
       "Appraisee_Marks": "11.11111111111111",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "2.2222222222222214",
       "Reviewer_Marks": "10"
   },
   {
       "KRA": "Mandatory Clause",
       "KPI": "Upskilling of Individual Learnings (Wtg-5)and of subordinates (Wtg-5). Benchmark 1 number in a year",
       "Remarks_/_Scoring_Logic": "Learn one new thing/new technology every 6months",
       "Unit": "%",
       "Type_of_KPI": "Positive",
       "Weightage": "10",
       "Target": "1",
       "Appraisee_Self_Rating": "220",
       "Appraisee_Marks": "10",
       "Appraiser_Rating": "20",
       "Appraiser_Marks": "10",
       "Reviewer_Marks": "10"
   }
]


for (let i = 0; i < newData.length; i++) {
 let dataItem = newData[i];

 for (let key in sum) {
 
   if (key in dataItem) {
   
     dataItem[key] = sum[key][i];
   }
 }
}


console.log(newData);

